### ISSUE TITLE
1.20 update

### ISSUE THREAD

**Issue by NCPUser** [KassuK1/BlackOut#25]
meteor client 1.20 minecraft Released!

**Comment by OLEPOSSU** [comment]
no shit bro

**Comment by diowz** [comment]
Dear NPCUser,

We hope this letter finds you in good health and high spirits. We, the BlackOut Addon development team, are writing to express our sincerest apologies for the delay in updating the addon to Minecraft version 1.20. We understand the frustration and inconvenience this may have caused to our valued users, and we take full responsibility for the extended timeline.

At BlackOut Addon, our primary goal has always been to provide a seamless and enjoyable gaming experience for our users. We strive to deliver regular updates that keep pace with the latest Minecraft versions, ensuring compatibility and exciting new features. However, in the case of the Minecraft version 1.20 update, we encountered unforeseen challenges that impeded our progress.

The development process for a Minecraft addon is complex and requires careful attention to detail. With the release of Minecraft version 1.20, several significant changes were introduced, necessitating substantial modifications to our addon. This unexpected scope of changes, combined with technical hurdles and other external factors, significantly delayed our update timeline.

Please be assured that our team has been working tirelessly to address these challenges and bring you an updated version of the BlackOut Addon that is fully compatible with Minecraft version 1.20. We have allocated additional resources and extended our development hours to expedite the process without compromising the quality or stability of the addon.

We deeply regret any inconvenience caused by this delay, and we understand the eagerness of our users to explore the latest features of Minecraft version 1.20 with the BlackOut Addon. We genuinely appreciate your patience and continued support during this time.

To demonstrate our commitment to providing an exceptional user experience, we would like to extend a token of appreciation to our loyal users. As soon as the updated version of the BlackOut Addon is released for Minecraft version 1.20, we will offer a limited-time discount on our premium features, as well as exclusive in-game rewards, as a gesture of gratitude for your understanding.

We assure you that the BlackOut Addon development team is working diligently to complete the update and make it available for download as soon as possible. We value your feedback and encourage you to reach out to us with any questions or concerns you may have regarding the delay or any other aspect of the addon.

Once again, we extend our deepest apologies for the inconvenience caused by the delay in updating the BlackOut Addon to Minecraft version 1.20. We sincerely appreciate your understanding and patience, and we look forward to delivering an enhanced and immersive gaming experience to you soon.

Thank you for being a part of the BlackOut Addon community.

Sincerely,

Diowz
BlackOut beta tester
BlackOut Addon Development Team

**Comment by KassuK1** [comment]
well update soon also diowz is not a developer

**Comment by NCPUser** [comment]
Ладно, можете не обновлять оставьте на 1.19.4 и делайте обновы на 1.20.1 тоже.
